project:
  type: website
  output-dir: docs

website:
  # title: "Dekartis"
  favicon: images/dekartis-web-logo.png


  navbar:
    logo: images/dekartis-web-logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



